version: '3.7'
services:

    mssql: 
        image: mcr.microsoft.com/mssql/server
        container_name: mssql
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=FortiaRules!

    rabbitmq:
        image: rabbitmq:3.7.15-management
        hostname: rabbitmq
        container_name: rabbitmq
        ports:
           - "5672:5672"
           - "15672:15672"

